### ISSUE TITLE
[Bug] Can't run cargo test

### ISSUE THREAD

**Issue by NicolasWent** [alloy-rs/alloy#626]
### Component

nodes

### What version of Alloy are you on?

Branch e4fb6691

### Operating System

Linux

### Describe the bug

After cloning alloy, when I try to run:

- `cargo test`
- `cargo test --all-features`
- `cargo test --no-default-features`

I am getting the following failed tests:
```
     Running unittests src/lib.rs (target/debug/deps/alloy_node_bindings-ff44a1c004dfb71e)

running 12 tests
test geth::tests::dev_mode ... FAILED
error: invalid value '0.5' for '--block-time <SECONDS>': invalid digit found in string

For more information, try '--help'.
test geth::tests::explicit_p2p_port ... FAILED
test geth::tests::clique_correctly_configured ... FAILED
test geth::tests::p2p_port ... FAILED
test geth::tests::test_extract_address ... ok
test geth::tests::port_0 ... FAILED
test anvil::tests::can_launch_anvil_with_more_accounts ... ok
test anvil::tests::assert_chain_id_without_rpc ... ok
test anvil::tests::assert_block_time_is_natural_number ... ok
test anvil::tests::can_launch_anvil ... ok
test anvil::tests::assert_chain_id ... ok
test anvil::tests::can_launch_anvil_with_sub_seconds_block_time ... FAILED

failures:

---- geth::tests::dev_mode stdout ----
thread 'geth::tests::dev_mode' panicked at crates/node-bindings/src/geth.rs:722:60:
called `Result::unwrap()` on an `Err` value: SpawnError(Os { code: 2, kind: NotFound, message: "No such file or directory" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- geth::tests::explicit_p2p_port stdout ----
thread 'geth::tests::explicit_p2p_port' panicked at crates/node-bindings/src/geth.rs:712:75:
called `Result::unwrap()` on an `Err` value: SpawnError(Os { code: 2, kind: NotFound, message: "No such file or directory" })

---- geth::tests::clique_correctly_configured stdout ----
thread 'geth::tests::clique_correctly_configured' panicked at crates/node-bindings/src/geth.rs:736:18:
called `Result::unwrap()` on an `Err` value: SpawnError(Os { code: 2, kind: NotFound, message: "No such file or directory" })

---- geth::tests::p2p_port stdout ----
thread 'geth::tests::p2p_port' panicked at crates/node-bindings/src/geth.rs:702:80:
called `Result::unwrap()` on an `Err` value: SpawnError(Os { code: 2, kind: NotFound, message: "No such file or directory" })

---- geth::tests::port_0 stdout ----
thread 'geth::tests::port_0' panicked at crates/node-bindings/src/geth.rs:681:68:
called `Result::unwrap()` on an `Err` value: SpawnError(Os { code: 2, kind: NotFound, message: "No such file or directory" })

---- anvil::tests::can_launch_anvil_with_sub_seconds_block_time stdout ----
thread 'anvil::tests::can_launch_anvil_with_sub_seconds_block_time' panicked at crates/node-bindings/src/anvil.rs:404:50:
called `Result::unwrap()` on an `Err` value: Timeout


failures:
    anvil::tests::can_launch_anvil_with_sub_seconds_block_time
    geth::tests::clique_correctly_configured
    geth::tests::dev_mode
    geth::tests::explicit_p2p_port
    geth::tests::p2p_port
    geth::tests::port_0

test result: FAILED. 6 passed; 6 failed; 0 ignored; 0 measured; 0 filtered out; finished in 10.00s

error: test failed, to rerun pass `-p alloy-node-bindings --lib`
```

Which makes all of the testsuite crash for me, so when I do modifications to alloy I can't test all of alloy and have to test the crate separately from others.

### Steps to reproduce

```console
➜ git clone https://github.com/alloy-rs/alloy.git
➜ cd alloy
➜ cargo test
```

### Os version

`Ubuntu 22.04.4 LTS`

**Comment by onbjerg** [comment]
Unfortunately running all of the tests requires having geth and anvil installed which is why these tests are failing for you 😓
